# Form implementation generated from reading ui file 'UI/host_info_input.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(110, 50, 183, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_host_ip = QtWidgets.QLineEdit(self.widget)
        self.le_host_ip.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px")
        self.le_host_ip.setObjectName("le_host_ip")
        self.verticalLayout_2.addWidget(self.le_host_ip)
        self.le_host_username = QtWidgets.QLineEdit(self.widget)
        self.le_host_username.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px")
        self.le_host_username.setObjectName("le_host_username")
        self.verticalLayout_2.addWidget(self.le_host_username)
        self.le_host_passwd = QtWidgets.QLineEdit(self.widget)
        self.le_host_passwd.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px")
        self.le_host_passwd.setObjectName("le_host_passwd")
        self.verticalLayout_2.addWidget(self.le_host_passwd)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(120, 210, 130, 36))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_ok = QtWidgets.QPushButton(self.widget1)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(self.widget1)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "主机ip"))
        self.label_3.setText(_translate("Form", "用户名"))
        self.label_2.setText(_translate("Form", "密码"))
        self.btn_ok.setText(_translate("Form", "确定"))
        self.btn_cancel.setText(_translate("Form", "取消"))
